### ISSUE TITLE
rails_best_practices (1.15.7) is not compatible with psych 2.0.13

### ISSUE THREAD

**Issue by smoothdvd** [railsbp/rails_best_practices#252]

**Comment by bf4** [comment]
Needs details and Ruby version

**Comment by prokizzle** [comment]
I'm also seeing this in Ruby 2.1.5

```
/Users/prokizzle/.gem/ruby/2.1.5/gems/rails_best_practices-1.15.7/lib/rails_best_practices/core/checks_loader.rb:22:in `checks_from_config': undefined method `load_file' for Psych:Module (NoMethodError)
	from /Users/prokizzle/.gem/ruby/2.1.5/gems/rails_best_practices-1.15.7/lib/rails_best_practices/core/checks_loader.rb:27:in `load_checks_from_config'
	from /Users/prokizzle/.gem/ruby/2.1.5/gems/rails_best_practices-1.15.7/lib/rails_best_practices/core/checks_loader.rb:11:in `load_lexicals'
	from /Users/prokizzle/.gem/ruby/2.1.5/gems/rails_best_practices-1.15.7/lib/rails_best_practices/core/runner.rb:48:in `initialize'
	from /Users/prokizzle/.gem/ruby/2.1.5/gems/rails_best_practices-1.15.7/lib/rails_best_practices/analyzer.rb:54:in `new'
	from /Users/prokizzle/.gem/ruby/2.1.5/gems/rails_best_practices-1.15.7/lib/rails_best_practices/analyzer.rb:54:in `analyze'
	from /Users/prokizzle/.gem/ruby/2.1.5/gems/rails_best_practices-1.15.7/lib/rails_best_practices/command.rb:136:in `<top (required)>'
	from /Users/prokizzle/.rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/prokizzle/.rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/prokizzle/.gem/ruby/2.1.5/gems/rails_best_practices-1.15.7/bin/rails_best_practices:6:in `<top (required)>'
	from /Users/prokizzle/.gem/ruby/2.1.5/bin/rails_best_practices:23:in `load'
	from /Users/prokizzle/.gem/ruby/2.1.5/bin/rails_best_practices:23:in `<main>'
```

**Comment by flyerhzm** [comment]
@prokizzle I tried ruby 2.2.2p95 and psych 2.0.13, didn't see such error
