### ISSUE TITLE
stack level too deep (SystemStackError)

### ISSUE THREAD

**Issue by iashanmugavel** [railsbp/rails_best_practices#258]
Hi,

I am getting the following error when I run rails best practices report genearation command. I am using Ruby 2.2.2 and rails 4.2.3

/usr/local/rvm/gems/ruby-2.2.2@nusdigital/gems/code_analyzer-0.4.5/lib/code_analyzer/sexp.rb:41:in `each': stack level too deep (SystemStackError)

**Comment by EmmaB** [comment]
I get something similar: 

```
(eval):4:in `sexp_type': stack level too deep (SystemStackError)=========================                                                                                                                 |
	from /Users/Emma/.rvm/gems/ruby-2.2.3/gems/code_analyzer-0.4.5/lib/code_analyzer/checking_visitor/default.rb:53:in `check_node'
```

**Comment by alagos** [comment]
The same here with ruby 2.2.5 and rails 5.1.3

```
 ~/workspace/productswatcher ➜ rails_best_practices
/home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/rails_best_practices-1.19.0/lib/rails_best_practices/core/methods.rb:58:in `each': stack level too deep (SystemStackError)
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/rails_best_practices-1.19.0/lib/rails_best_practices/core/methods.rb:58:in `find'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/rails_best_practices-1.19.0/lib/rails_best_practices/core/methods.rb:58:in `mark_parent_class_method_used'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/rails_best_practices-1.19.0/lib/rails_best_practices/core/methods.rb:60:in `mark_parent_class_method_used'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/rails_best_practices-1.19.0/lib/rails_best_practices/core/methods.rb:60:in `mark_parent_class_method_used'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/rails_best_practices-1.19.0/lib/rails_best_practices/core/methods.rb:60:in `mark_parent_class_method_used'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/rails_best_practices-1.19.0/lib/rails_best_practices/core/methods.rb:60:in `mark_parent_class_method_used'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/rails_best_practices-1.19.0/lib/rails_best_practices/core/methods.rb:60:in `mark_parent_class_method_used'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/gems/rails_best_practices-1.19.0/lib/rails_best_practices/core/methods.rb:60:in `mark_parent_class_method_used'
         ... 7702 levels...
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/bin/rails_best_practices:23:in `load'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/bin/rails_best_practices:23:in `<main>'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/bin/ruby_executable_hooks:15:in `eval'
        from /home/alter/.rvm/gems/ruby-2.2.5@productwatcher/bin/ruby_executable_hooks:15:in `<main>'

```

**Comment by alagos** [comment]
Checking deeper with `-d` modifier, the problem was in:
```
module Endpoint
  class ApplicationController < ApplicationController

```
I changed to 
```
module Endpoint
  class ApplicationController < ::ApplicationController

```
and it worked
