### ISSUE TITLE
Ruby 2.3 issue - undefined method `this' for #<Gem::Specification:0x1315bcc rails_best_practices-1.17.0

### ISSUE THREAD

**Issue by bogdanRada** [railsbp/rails_best_practices#279]
Here is the backtrace:
```ruby
/home/raul/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x1315bcc rails_best_practices-1.17.0> (NoMethodError)
	from /home/raul/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
	from /home/raul/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
	from /home/raul/.rvm/gems/ruby-2.3.1@my_project/gems/rails_best_practices-1.17.0/bin/rails_best_practices:5:in `<top (required)>'

```

  - RUBYGEMS VERSION: 2.5.1
  - RUBY VERSION: 2.3.1 (2016-04-26 patchlevel 112) [x86_64-linux]

Any help would be appreciated

**Comment by ingmaras** [comment]
Same here.

**Comment by wuzzzzaah** [comment]
Hey guys, I encountered this issue too. 
You need to update rubygems, just run `gem update --system` and it should resolve this issue.

Cheers!

**Comment by bogdanRada** [comment]
thanks @wuzzzzaah , that worked, updated rubygems from 2.5.1 to 2.6.6 and works now.
Thanks a lot :)
